name: .NET Core Build Workflow

on:
  push:
    branches: [ main ]
  schedule:
    # Executa às 00:00 UTC a cada 2 dias
    - cron: '0 0 */2 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Encontrar arquivo de solução
      id: find-sln
      run: |
        echo "SOLUTION_FILE=$(find . -type f -name "*.sln" -o -name "*.csproj" | head -n 1)" >> $GITHUB_ENV
        if [ -z "$SOLUTION_FILE" ]; then
          echo "Nenhum arquivo .sln ou .csproj encontrado no repositório"
          exit 1
        fi
        echo "Arquivo encontrado: $SOLUTION_FILE"

    - name: Build do projeto
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release